version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "testValue1"
  exportedVariables:
    - testEnv
steps:
  - type: Command
    timeoutInSeconds: 400
    name: "trtdtd"
    command: |
      export testEnv=123
      echo $testEnv > output1.txt
  - type: Command
    timeoutInSeconds: 400
    name: "build"
    command: |
      echo Build started on `date`
      chmod +x gradlew
      ./gradlew build

outputArtifacts:
  - name: output1
    type: BINARY
    location: output1.txt

 
